name: Exploring and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    #DOCKER_USERNAME: 20150748
    IMAGE_NAME: github-actions-nginx
    x: 5
jobs:
    docker:
        runs-on: ubuntu-latest
        
        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
              
            
            - name: Docker Login $x
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$CONTAINER_USERNAME/$IMAGE_NAME:latest
            
    deploy:
        needs: docker
        runs-on: ubuntu-latest 
        steps:
            - name: dicker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
              
              
        
        
        
        